server:
  port: 8081
  servlet.context-path: /jackpot

application:
  teste: A,B,C,D,E,F


spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true
    properties:
      hibernate:
        show_sql: false
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/jackpot
    username: engine
    password: engine1
    type: com.zaxxer.hikari.HikariDataSource
    connection-test-query: select 1
    connection-timeout: 25200
    minimum-idle: 1
    maximum-pool-size: 10
  zipkin.enabled: false



